/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var Filter = kurentoClient.register.abstracts.Filter;


/**
 * Create an element
 *
 * @classdesc
 *  KmsDetectFaces interface. Documentation about the module
 *
 * @extends module:core/abstracts.Filter
 *
 * @constructor module:datachannelexample.KmsDetectFaces
 */
function KmsDetectFaces(){
  KmsDetectFaces.super_.call(this);
};
inherits(KmsDetectFaces, Filter);


/**
 * @alias module:datachannelexample.KmsDetectFaces.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link module:core.MediaPipeline MediaPipeline}
 */
KmsDetectFaces.constructorParams = {
  mediaPipeline: {
    type: 'kurento.MediaPipeline',
    required: true
  }
};

/**
 * @alias module:datachannelexample.KmsDetectFaces.events
 *
 * @extends module:core/abstracts.Filter.events
 */
KmsDetectFaces.events = Filter.events;


/**
 * Checker for {@link module:datachannelexample.KmsDetectFaces}
 *
 * @memberof module:datachannelexample
 *
 * @param {external:String} key
 * @param {module:datachannelexample.KmsDetectFaces} value
 */
function checkKmsDetectFaces(key, value)
{
  if(!(value instanceof KmsDetectFaces))
    throw ChecktypeError(key, KmsDetectFaces, value);
};


module.exports = KmsDetectFaces;

KmsDetectFaces.check = checkKmsDetectFaces;
