/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of the GNU Lesser General Public License (LGPL)
 * version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var Filter = kurentoClient.register.abstracts.Filter;


/**
 * Create an element
 *
 * @classdesc
 *  KmsDetectFaces interface. Documentation about the module
 *
 * @extends module:core/abstracts.Filter
 *
 * @constructor module:datachannelexample.KmsDetectFaces
 */
function KmsDetectFaces(){
  KmsDetectFaces.super_.call(this);
};
inherits(KmsDetectFaces, Filter);


/**
 * @alias module:datachannelexample.KmsDetectFaces.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link module:core.MediaPipeline MediaPipeline}
 */
KmsDetectFaces.constructorParams = {
  mediaPipeline: {
    type: 'MediaPipeline',
    required: true
  }
};

/**
 * @alias module:datachannelexample.KmsDetectFaces.events
 *
 * @extends module:core/abstracts.Filter.events
 */
KmsDetectFaces.events = Filter.events;


/**
 * Checker for {@link module:datachannelexample.KmsDetectFaces}
 *
 * @memberof module:datachannelexample
 *
 * @param {external:String} key
 * @param {module:datachannelexample.KmsDetectFaces} value
 */
function checkKmsDetectFaces(key, value)
{
  if(!(value instanceof KmsDetectFaces))
    throw ChecktypeError(key, KmsDetectFaces, value);
};


module.exports = KmsDetectFaces;

KmsDetectFaces.check = checkKmsDetectFaces;
