/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (https://kurento.openvidu.io/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var Filter = kurentoClient.register.abstracts.Filter;


/**
 * Create an element
 *
 * @classdesc
 *  KmsShowFaces interface. Documentation about the module
 *
 * @extends module:core/abstracts.Filter
 *
 * @constructor module:datachannelexample.KmsShowFaces
 */
function KmsShowFaces(){
  KmsShowFaces.super_.call(this);
};
inherits(KmsShowFaces, Filter);


/**
 * @alias module:datachannelexample.KmsShowFaces.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link MediaPipeline}
 */
KmsShowFaces.constructorParams = {
  mediaPipeline: {
    type: 'kurento.MediaPipeline',
    required: true
  }
};

/**
 * @alias module:datachannelexample.KmsShowFaces.events
 *
 * @extends module:core/abstracts.Filter.events
 */
KmsShowFaces.events = Filter.events;


/**
 * Checker for {@link module:datachannelexample.KmsShowFaces}
 *
 * @memberof module:datachannelexample
 *
 * @param {external:String} key
 * @param {module:datachannelexample.KmsShowFaces} value
 */
function checkKmsShowFaces(key, value)
{
  if(!(value instanceof KmsShowFaces))
    throw ChecktypeError(key, KmsShowFaces, value);
};


module.exports = KmsShowFaces;

KmsShowFaces.check = checkKmsShowFaces;
