/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of the GNU Lesser General Public License (LGPL)
 * version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var Filter = kurentoClient.register.abstracts.Filter;


/**
 * Create an element
 *
 * @classdesc
 *  KmsShowFaces interface. Documentation about the module
 *
 * @extends module:core/abstracts.Filter
 *
 * @constructor module:datachannelexample.KmsShowFaces
 */
function KmsShowFaces(){
  KmsShowFaces.super_.call(this);
};
inherits(KmsShowFaces, Filter);


/**
 * @alias module:datachannelexample.KmsShowFaces.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link module:core.MediaPipeline MediaPipeline}
 */
KmsShowFaces.constructorParams = {
  mediaPipeline: {
    type: 'MediaPipeline',
    required: true
  }
};

/**
 * @alias module:datachannelexample.KmsShowFaces.events
 *
 * @extends module:core/abstracts.Filter.events
 */
KmsShowFaces.events = Filter.events;


/**
 * Checker for {@link module:datachannelexample.KmsShowFaces}
 *
 * @memberof module:datachannelexample
 *
 * @param {external:String} key
 * @param {module:datachannelexample.KmsShowFaces} value
 */
function checkKmsShowFaces(key, value)
{
  if(!(value instanceof KmsShowFaces))
    throw ChecktypeError(key, KmsShowFaces, value);
};


module.exports = KmsShowFaces;

KmsShowFaces.check = checkKmsShowFaces;
