/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (https://kurento.openvidu.io/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var MediaElement = kurentoClient.register.abstracts.MediaElement;


/**
 * Create an element
 *
 * @classdesc
 *  KmsSendData interface. Documentation about the module
 *
 * @extends module:core/abstracts.MediaElement
 *
 * @constructor module:datachannelexample.KmsSendData
 */
function KmsSendData(){
  KmsSendData.super_.call(this);
};
inherits(KmsSendData, MediaElement);


/**
 * @alias module:datachannelexample.KmsSendData.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link MediaPipeline}
 */
KmsSendData.constructorParams = {
  mediaPipeline: {
    type: 'kurento.MediaPipeline',
    required: true
  }
};

/**
 * @alias module:datachannelexample.KmsSendData.events
 *
 * @extends module:core/abstracts.MediaElement.events
 */
KmsSendData.events = MediaElement.events;


/**
 * Checker for {@link module:datachannelexample.KmsSendData}
 *
 * @memberof module:datachannelexample
 *
 * @param {external:String} key
 * @param {module:datachannelexample.KmsSendData} value
 */
function checkKmsSendData(key, value)
{
  if(!(value instanceof KmsSendData))
    throw ChecktypeError(key, KmsSendData, value);
};


module.exports = KmsSendData;

KmsSendData.check = checkKmsSendData;
