/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of the GNU Lesser General Public License (LGPL)
 * version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var MediaElement = kurentoClient.register.abstracts.MediaElement;


/**
 * Create an element
 *
 * @classdesc
 *  KmsShowData interface. Documentation about the module
 *
 * @extends module:core/abstracts.MediaElement
 *
 * @constructor module:datachannelexample.KmsShowData
 */
function KmsShowData(){
  KmsShowData.super_.call(this);
};
inherits(KmsShowData, MediaElement);


/**
 * @alias module:datachannelexample.KmsShowData.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link module:core.MediaPipeline MediaPipeline}
 */
KmsShowData.constructorParams = {
  mediaPipeline: {
    type: 'MediaPipeline',
    required: true
  }
};

/**
 * @alias module:datachannelexample.KmsShowData.events
 *
 * @extends module:core/abstracts.MediaElement.events
 */
KmsShowData.events = MediaElement.events;


/**
 * Checker for {@link module:datachannelexample.KmsShowData}
 *
 * @memberof module:datachannelexample
 *
 * @param {external:String} key
 * @param {module:datachannelexample.KmsShowData} value
 */
function checkKmsShowData(key, value)
{
  if(!(value instanceof KmsShowData))
    throw ChecktypeError(key, KmsShowData, value);
};


module.exports = KmsShowData;

KmsShowData.check = checkKmsShowData;
